
[functions.determine-user-ability]
enabled = true
verify_jwt = true
import_map = "./functions/determine-user-ability/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/determine-user-ability/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/determine-user-ability/*.html" ]

[functions.generate-user-profile]
enabled = true
verify_jwt = true
import_map = "./functions/generate-user-profile/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-user-profile/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-user-profile/*.html" ]

[functions.modify-program-session]
enabled = true
verify_jwt = false
import_map = "./functions/modify-program-session/deno.json"
entrypoint = "./functions/modify-program-session/index.ts"

[functions.training-assistant]
enabled = true
verify_jwt = false
import_map = "./functions/training-assistant/deno.json"
entrypoint = "./functions/training-assistant/index.ts"
