import { Workout } from './types';

export const exerciseDatabase = [
  'Double Unders', 'Wall Balls', 'Snatch', 'Rowing Calories', 'Chest to Bar Pull-ups',
  'Pull-ups', 'Alternating Dumbbell Snatches', 'Handstand Push-ups', 'Deadlifts',
  'Overhead Squats', 'Thrusters', 'Dumbbell Thrusters', 'Burpees', 'Toes to Bar',
  'Power Cleans', 'Burpee Box Jump Overs', 'Box Jumps', 'Box Jump Overs',
  'Clean and Jerks', 'Dumbbell Clean and Jerk', 'Ring Muscle Ups',
  'Rope Climbs', 'Legless Rope Climbs', 'GHD Sit-ups', 'Kettlebell Swings', 'Kettlebell Snatches',
  'Bike Calories', 'Ski Calories', 'Squat Cleans', 'Squat Snatch', 'Power Snatch', 'Bar Muscle Ups', 'Dumbbell Box Step-Ups', 'Push-ups', 'Strict Pull-ups'
];

export const exerciseEquipment: { [key: string]: string[] } = {
  'Strict Pull-ups': ['Pullup Bar or Rig', 'Low or Adjustable Rings'],
  'Push-ups': [],
  'Double Unders': ['Jump Rope'],
  'Single Unders': ['Jump Rope'],
  'Wall Balls': ['Wall Ball', 'Wall Space'],
  'Toes to Bar': ['Pullup Bar or Rig'],
  'Hanging Knee Raise': ['Pullup Bar or Rig'],
  'Wall Walks': ['Wall Space'],
  'Pull-ups': ['Pullup Bar or Rig'],
  'Chest to Bar Pull-ups': ['Pullup Bar or Rig'],
  'Strict Handstand Push-ups': ['Wall Space'],
  'Wall-Facing Handstand Push-ups': ['Wall Space'],
  'Deficit Handstand Push-ups': ['Wall Space'],
  'Bar Muscle Ups': ['Pullup Bar or Rig'],
  'Rope Climbs': ['Climbing Rope'],
  'Strict Ring Dips': ['High Rings', 'Low or Adjustable Rings'],
  'Ring Dips': ['High Rings', 'Low or Adjustable Rings'],
  'Ring Muscle Ups': ['High Rings'],
  'Alternating Pistols': [],
  'GHD Sit-ups': ['GHD'],
  'Sit-ups': [],
  'Handstand Walk': ['Open Space'],
  'Legless Rope Climbs': ['Climbing Rope'],
  'Strict Ring Muscle Ups': ['High Rings'],
  'Seated Legless Rope Climbs': ['Climbing Rope'],
  'Pegboard Ascent': ['Pegboard'],
  'Handstand Walk over Obstacle': ['HS Walk Obstacle'],
  'Hang Snatch': ['Barbell'],
  'Ground to Overhead': ['Barbell'],
  'Hang Cleans': ['Barbell'],
  'Hang Power Cleans': ['Barbell'],
  'Thrusters': ['Barbell'],
  'Power Snatch': ['Barbell'],
  'Cleans': ['Barbell'],
  'Clean & Jerks': ['Barbell'],
  'Snatch': ['Barbell'],
  'Power Clean': ['Barbell'],
  'Clean': ['Barbell'],
  'Jerk': ['Barbell', 'Squat Rack'],
  'Back Squat': ['Barbell', 'Squat Rack'],
  'Front Squat': ['Barbell', 'Squat Rack'],
  'Overhead Squats': ['Barbell', 'Squat Rack'],
  'Deadlifts': ['Barbell', 'Squat Rack'],
  'Bench Press': ['Barbell', 'Bench'],
  'Push Press': ['Barbell'],
  'Dumbbell Overhead Walking Lunges': ['Dumbbells'],
  'Dumbbell Walking Lunges': ['Dumbbells'],
  'DBall Over Shoulder': ['DBall'],
  'Dball Carries': ['DBall'],
  'Dip Bar Dips': ['Dip Bar'],
  'Farmers Carry': ['Dumbbells'],
  'Overhead Walking Lunges': ['Barbell'],
  'Ring Rows': ['Low or Adjustable Rings'],
  'Sandbag Carry': ['Sandbag'],
  'Air Bike': ['Air Bike'],
  'Air Squats': [],
  'Air Squats (weighted)': ['Dumbbells'],
  'Alternating Dumbbell Snatches': ['Dumbbells'],
  'Axle Front Rack Lunge': ['Axle Bar'],
  'Axle Shoulder to Overhead': ['Axle Bar'],
  'Bar Facing Burpees': ['Barbell'],
  'Burpees': [],
  'Bike Erg': ['Bike Erg'],
  'Box Jumps': ['Plyo Box'],
  'Box Jump Overs': ['Plyo Box'],
  'Box Step-ups': ['Plyo Box'],
  'Burpee Box Jump Overs': ['Plyo Box'],
  'Burpee Bar Muscle Ups': ['Pullup Bar or Rig'],
  'Burpee Ring Muscle Ups': ['High Rings'],
  'Burpee Pull Ups': ['Pullup Bar or Rig'],
  'Burpees over Dumbbell': ['Dumbbells'],
  'Crossover Double Unders': ['Jump Rope'],
  'Dumbbell Box Step Over': ['Dumbbells', 'Plyo Box'],
  'Dumbbell Box Step-Ups': ['Dumbbells', 'Plyo Box'],
  'Dumbbell Clean and Jerk': ['Dumbbells'],
  'Dumbbell Snatch': ['Dumbbells'],
  'Dumbbell Deadlift': ['Dumbbells'],
  'Dumbbell Cleans': ['Dumbbells'],
  'Dumbbell Hang Clean and Jerks': ['Dumbbells'],
  'Dumbbell Shoulder to Overhead': ['Dumbbells'],
  'Dumbbell Hang Power Cleans': ['Dumbbells'],
  'Dumbbell Hang Squat Cleans': ['Dumbbells'],
  'Dumbbell Squats': ['Dumbbells'],
  'Dumbbell Thrusters': ['Dumbbells'],
  'Front Rack Walking Lunges': ['Barbell'],
  'Handstand Push-ups': ['Wall Space'],
  'Double Kettlebell Deadlifts': ['Kettlebells'],
  'Kettlebell Snatch': ['Kettlebells'],
  'Kettlebell Swings': ['Kettlebells'],
  'Rowing Distance': ['Rowing Machine'],
  'Rowing Calories': ['Rowing Machine'],
  'Run': [],
  'Sandbag Clean': ['Sandbag'],
  'Shoulder to Overhead': ['Barbell'],
  'Shuttle Runs': ['Open Space'],
  'Single Dumbbell Overhead Squat': ['Dumbbells'],
  'Ski Erg': ['Ski Erg'],
  'Sprint': [],
  'Squat Cleans': ['Barbell'],
  'Squat Snatch': ['Barbell'],
  'Strict Deficit Handstand Push-ups': ['Wall Space'],
  'V-ups': [],
  'Walking Lunges': [],
  'Weighted Walking Lunges': ['Dumbbells'],
  'Handstand Walk': ['Open Space'],
  'Rest': [],
  'Lateral Burpee Box Jump Overs': ['Plyo Box']
};
